### ISSUE TITLE
A typo on the pre-processing - pH values for RFPs

### ISSUE THREAD

**Issue by miguelgondu** [samuelstanton/lambo#11]
Hi, `lambo` authors.

First of all, thanks for making your code open source. Really interesting work!

I'm currently working on replicating your RFP experiment, and I think I've found a small typo on the preprocessing: When you get the info about the `pdb`s using `pypdb`, there's a typo on the `get_pH` function:

```python
# Current implementation
def get_pH(info):
    try:
        return info['expt1_crystal_grow']['ph']
    except KeyError:
        return float('NaN')
```

I think you meant `info['exptl_crystal_grow'][0]['p_h']`. The `1` instead of the `l` is likely throwing a `KeyError` for all entries. In other words, you ran `foldx` with all proteins assuming a pH of 7.0, but some of them actually have different pH values. For example, `2vvh` crystal's pH is `8.4`.

Still I don't think it'd change the stability and SASA results all that much.

**Comment by samuelstanton** [comment]
Thanks for reporting the issue and your patience, [fixed](https://github.com/samuelstanton/lambo/commit/ac62e8e86c2068f8ac3c60fea4e356773291b6ec)
