### ISSUE TITLE
mask_ratio during mutation

### ISSUE THREAD

**Issue by kkyamada** [samuelstanton/lambo#5]
I am trying to use the LaMBO model with MLM decoding. In the code, the MLM optimization step uses mask_ratio defined in the config, but during the mutation step in lambo.py (from line246 to line249), it doesn't seem to introduce more than one mask per sequence.
```
elif self.position_sampler == 'uniform':
                    mask_idxs = np.concatenate([
                        random.choice(w_idxs) for w_idxs in window_mask_idxs.values()
                    ])
```
Is this something intended? Do you think setting the mutation ratio same as the MLM optimization step would make the exploration  more efficient, or collapse the latent feature optimization?

Thanks!

**Comment by samuelstanton** [comment]
great question!

you're right that the mask_ratio defined in the config is passed to the optimizer and stored as an attribute here

https://github.com/samuelstanton/lambo/blob/main/lambo/optimizers/lambo.py#L50

I don't actually use the attribute anywhere in the optimizer, only for training the MLM head, it's a vestigial artifact of other things I've tried. Currently you can control the size of the mask with the `optimizer.window_size` config attribute, but that increases the width of a single contiguous mask. 

There's two reasons things are done this way. Changing a couple tokens at a time speeds up convergence. If you masked say 10% of the tokens instead at random positions, it would speed up exploration globally but slow it down locally.

The other reason is originally I was interested in selecting mutation positions in a more deliberate way by computing statistics of a sliding window across the sequence. I didn't make much progress there, so I reverted to sampling a single contiguous window uniformly at random.

**Comment by kkyamada** [comment]
Thank you so much! It really helps!
